# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 8 CI

on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches:
      - master                      # Specific branch (master)
      - develop                     # Specific branch (develop)
      - 'feature/*'                 # Any branch that starts with 'feature/'
      - 'release/*'                 # Any branch that starts with 'release/'
  pull_request:
    branches:
      - master                      # Trigger on pull requests to the master branch
      - develop                     # Trigger on pull requests to the develop branch
      - 'feature/*'                 # PRs to feature branches
      - 'release/*'                 # PRs to release branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Core SDK 8.0
      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Use .NET 8.0 SDK

      - name: Restore dependencies
        run: dotnet restore ./src/LicensingERP.sln

      - name: Build project
        run: dotnet build --configuration Release --no-restore ./src/LicensingERP.sln
        
       # Add CodeQL initialization
      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp'

      # Perform CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: 'security'

      # Upload CodeQL results (optional, for viewing in the Security tab)
      #- name: Upload CodeQL results
      #  uses: github/codeql-action/upload-results@v2
