# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 8 CI

on:
  push:
    branches:
      - main                   # Specific branch (main)
      - 'feature/*'             # Any branch that starts with 'feature/'
      - 'release/*'             # Any branch that starts with 'release/'
  pull_request:
    branches:
      - main                   # Trigger on pull requests to the main branch
      - 'feature/*'             # PRs to feature branches
      - 'release/*'             # PRs to release branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
		# Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Core SDK 8.0
      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Use .NET 8.0 SDK

	  # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

  	  # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

    #- name: Build project
      #run: dotnet build --no-restore
    
